name: CI

# silverstripe/gha-ci builds the job matrix (PHP versions, databases, the --prefer-lowest job) from composer.json
# and the branch name.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
